site_name: Fast Action Links
repo_url: https://github.com/PalanteJon/org.takethestreets.fastactionlinks
theme: material

pages:
- Home: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
pages:
  - Installation: index.md
  - Quick Start: quick-start.md
